-- MySQL Script generated by MySQL Workbench
-- Sun Apr 18 19:09:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hejevero_principal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hejevero_principal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hejevero_principal` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `hejevero_principal` ;

-- -----------------------------------------------------
-- Table `hejevero_principal`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`user` (
  `Id_user` INT NOT NULL AUTO_INCREMENT,
  `Nick_user` VARCHAR(20) NULL,
  `Pass_user` VARCHAR(20) NULL,
  `Reg_user` VARCHAR(10) NULL,
  `Sta_user` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`country` (
  `Id_cou` INT NOT NULL AUTO_INCREMENT,
  `Nam_cou` VARCHAR(250) NULL,
  `Sta_cou` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_cou`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`state` (
  `Id_sta` INT NOT NULL AUTO_INCREMENT,
  `Nam_sta` VARCHAR(250) NULL,
  `Num_sta` VARCHAR(5) NULL,
  `Sta_sta` VARCHAR(5) NULL,
  `country_Id_cou` INT NOT NULL,
  PRIMARY KEY (`Id_sta`),
  INDEX `fk_State_country1_idx` (`country_Id_cou` ASC),
  CONSTRAINT `fk_State_country1`
    FOREIGN KEY (`country_Id_cou`)
    REFERENCES `hejevero_principal`.`country` (`Id_cou`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`city` (
  `Id_city` INT NOT NULL AUTO_INCREMENT,
  `Nam_city` VARCHAR(250) NULL,
  `Sta_city` VARCHAR(5) NULL,
  `state_Id_sta` INT NOT NULL,
  PRIMARY KEY (`Id_city`),
  INDEX `fk_city_State1_idx` (`state_Id_sta` ASC),
  CONSTRAINT `fk_city_State1`
    FOREIGN KEY (`state_Id_sta`)
    REFERENCES `hejevero_principal`.`state` (`Id_sta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`user_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`user_data` (
  `Id_ud` INT NOT NULL AUTO_INCREMENT,
  `Num_ud` VARCHAR(45) NULL,
  `Bir_ud` VARCHAR(10) NULL,
  `Nam_ud` VARCHAR(250) NULL,
  `LaN_ud` VARCHAR(250) NULL,
  `Pic_ud` VARCHAR(250) NULL,
  `Mail_ud` VARCHAR(250) NULL,
  `Con_ud` VARCHAR(15) NULL,
  `Dir_ud` VARCHAR(45) NULL,
  `Sta_ud` VARCHAR(5) NULL,
  `user_Id_user` INT NOT NULL,
  `city_Id_city` INT NOT NULL,
  PRIMARY KEY (`Id_ud`),
  INDEX `fk_user-data_user1_idx` (`user_Id_user` ASC),
  INDEX `fk_user-data_city1_idx` (`city_Id_city` ASC),
  CONSTRAINT `fk_user-data_user1`
    FOREIGN KEY (`user_Id_user`)
    REFERENCES `hejevero_principal`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user-data_city1`
    FOREIGN KEY (`city_Id_city`)
    REFERENCES `hejevero_principal`.`city` (`Id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`role` (
  `Id_role` INT NOT NULL AUTO_INCREMENT,
  `Nam_role` VARCHAR(250) NULL,
  `Sta_role` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`function` (
  `Id_fun` INT NOT NULL AUTO_INCREMENT,
  `Nam_fun` VARCHAR(250) NULL,
  `Sta_fun` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_fun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`calendar` (
  `Id_cal` INT NOT NULL AUTO_INCREMENT,
  `Nam_cal` VARCHAR(250) NULL,
  `Num_cal` INT NULL,
  `Sta_cal` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_cal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`month`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`month` (
  `Id_mon` INT NOT NULL AUTO_INCREMENT,
  `Cod_mon` VARCHAR(10) NULL,
  `Nam_mon` VARCHAR(250) NULL,
  `Sta_mon` VARCHAR(5) NULL,
  `calendar_Id_cal` INT NOT NULL,
  PRIMARY KEY (`Id_mon`),
  INDEX `fk_month_calendar1_idx` (`calendar_Id_cal` ASC),
  CONSTRAINT `fk_month_calendar1`
    FOREIGN KEY (`calendar_Id_cal`)
    REFERENCES `hejevero_principal`.`calendar` (`Id_cal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`day` (
  `Id_day` INT NOT NULL AUTO_INCREMENT,
  `Cod_day` VARCHAR(10) NULL,
  `Nam_day` VARCHAR(250) NULL,
  `Sta_day` VARCHAR(5) NULL,
  `month_Id_mon` INT NOT NULL,
  PRIMARY KEY (`Id_day`),
  INDEX `fk_day_month1_idx` (`month_Id_mon` ASC),
  CONSTRAINT `fk_day_month1`
    FOREIGN KEY (`month_Id_mon`)
    REFERENCES `hejevero_principal`.`month` (`Id_mon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`type` (
  `Id_type` INT NOT NULL AUTO_INCREMENT,
  `Nam_type` VARCHAR(250) NULL,
  `Sta_type` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`company` (
  `Id_com` INT NOT NULL AUTO_INCREMENT,
  `Num_com` VARCHAR(45) NULL,
  `Nam_com` VARCHAR(250) NULL,
  `Tur_com` VARCHAR(250) NULL,
  `Dat_com` VARCHAR(10) NULL,
  `Sta_com` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_com`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`post` (
  `Id_post` INT NOT NULL AUTO_INCREMENT,
  `Cod_post` VARCHAR(10) NULL,
  `Nam_post` VARCHAR(250) NULL,
  `SNam_post` VARCHAR(250) NULL,
  `Dat_post` VARCHAR(10) NULL,
  `End_post` VARCHAR(45) NULL,
  `Det_post` VARCHAR(500) NULL,
  `SDet_post` VARCHAR(500) NULL,
  `Sta_post` VARCHAR(5) NULL,
  `user_Id_user` INT NOT NULL,
  `day_Id_day` INT NOT NULL,
  `type_Id_type` INT NOT NULL,
  `company_Id_com` INT NOT NULL,
  PRIMARY KEY (`Id_post`),
  INDEX `fk_post_user2_idx` (`user_Id_user` ASC),
  INDEX `fk_post_day1_idx` (`day_Id_day` ASC),
  INDEX `fk_post_type1_idx` (`type_Id_type` ASC),
  INDEX `fk_post_company1_idx` (`company_Id_com` ASC),
  CONSTRAINT `fk_post_user2`
    FOREIGN KEY (`user_Id_user`)
    REFERENCES `hejevero_principal`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_day1`
    FOREIGN KEY (`day_Id_day`)
    REFERENCES `hejevero_principal`.`day` (`Id_day`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_type1`
    FOREIGN KEY (`type_Id_type`)
    REFERENCES `hejevero_principal`.`type` (`Id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_company1`
    FOREIGN KEY (`company_Id_com`)
    REFERENCES `hejevero_principal`.`company` (`Id_com`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`record` (
  `Id_rec` INT NOT NULL AUTO_INCREMENT,
  `Cod_rec` VARCHAR(10) NULL,
  `Nam_rec` VARCHAR(250) NULL,
  `Tab_rec` VARCHAR(250) NULL,
  `IdCha_rec` INT NULL,
  `Sta_rec` VARCHAR(5) NULL,
  `user_Id_user` INT NOT NULL,
  PRIMARY KEY (`Id_rec`),
  INDEX `fk_record_user3_idx` (`user_Id_user` ASC),
  CONSTRAINT `fk_record_user3`
    FOREIGN KEY (`user_Id_user`)
    REFERENCES `hejevero_principal`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`system` (
  `Id_sys` INT NOT NULL AUTO_INCREMENT,
  `Sta_sys` VARCHAR(5) NULL,
  `user_Id_user` INT NOT NULL,
  `role_Id_role` INT NOT NULL,
  PRIMARY KEY (`Id_sys`),
  INDEX `fk_system_user2_idx` (`user_Id_user` ASC),
  INDEX `fk_system_role1_idx` (`role_Id_role` ASC),
  CONSTRAINT `fk_system_user2`
    FOREIGN KEY (`user_Id_user`)
    REFERENCES `hejevero_principal`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_system_role1`
    FOREIGN KEY (`role_Id_role`)
    REFERENCES `hejevero_principal`.`role` (`Id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`priority` (
  `Id_prio` INT NOT NULL AUTO_INCREMENT,
  `Pub_prio` VARCHAR(250) NULL,
  `Tab_prio` VARCHAR(250) NULL,
  `Sta_prio` VARCHAR(5) NULL,
  `function_Id_fun` INT NOT NULL,
  PRIMARY KEY (`Id_prio`),
  INDEX `fk_priority_function2_idx` (`function_Id_fun` ASC),
  CONSTRAINT `fk_priority_function2`
    FOREIGN KEY (`function_Id_fun`)
    REFERENCES `hejevero_principal`.`function` (`Id_fun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`role_priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`role_priority` (
  `Id_rp` INT NOT NULL AUTO_INCREMENT,
  `Sta_rp` VARCHAR(5) NULL,
  `priority_Id_prio` INT NOT NULL,
  `role_Id_role` INT NOT NULL,
  PRIMARY KEY (`Id_rp`),
  INDEX `fk_rol_priority_priority1_idx` (`priority_Id_prio` ASC),
  INDEX `fk_role_priority_role1_idx` (`role_Id_role` ASC),
  CONSTRAINT `fk_rol_priority_priority1`
    FOREIGN KEY (`priority_Id_prio`)
    REFERENCES `hejevero_principal`.`priority` (`Id_prio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_priority_role1`
    FOREIGN KEY (`role_Id_role`)
    REFERENCES `hejevero_principal`.`role` (`Id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`role_user_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`role_user_company` (
  `Id_ruc` INT NOT NULL AUTO_INCREMENT,
  `Sta_ruc` VARCHAR(5) NULL,
  `user_Id_user` INT NOT NULL,
  `role_Id_role` INT NOT NULL,
  `company_Id_com` INT NOT NULL,
  PRIMARY KEY (`Id_ruc`),
  INDEX `fk_rol_user_warehouse_user1_idx` (`user_Id_user` ASC),
  INDEX `fk_rol_user_company_role1_idx` (`role_Id_role` ASC),
  INDEX `fk_rol_user_company_company1_idx` (`company_Id_com` ASC),
  CONSTRAINT `fk_rol_user_warehouse_user1`
    FOREIGN KEY (`user_Id_user`)
    REFERENCES `hejevero_principal`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_user_company_role1`
    FOREIGN KEY (`role_Id_role`)
    REFERENCES `hejevero_principal`.`role` (`Id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_user_company_company1`
    FOREIGN KEY (`company_Id_com`)
    REFERENCES `hejevero_principal`.`company` (`Id_com`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`warehouse` (
  `Id_wh` INT NOT NULL AUTO_INCREMENT,
  `Nam_wh` VARCHAR(250) NULL,
  `Cod_wh` VARCHAR(10) NULL,
  `Dat_wh` VARCHAR(10) NULL,
  `Dir_wh` VARCHAR(250) NULL,
  `Sta_wh` VARCHAR(5) NULL,
  `company_Id_com` INT NOT NULL,
  `city_Id_city` INT NOT NULL,
  PRIMARY KEY (`Id_wh`),
  INDEX `fk_warehouse_company1_idx` (`company_Id_com` ASC),
  INDEX `fk_warehouse_city1_idx` (`city_Id_city` ASC),
  CONSTRAINT `fk_warehouse_company1`
    FOREIGN KEY (`company_Id_com`)
    REFERENCES `hejevero_principal`.`company` (`Id_com`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warehouse_city1`
    FOREIGN KEY (`city_Id_city`)
    REFERENCES `hejevero_principal`.`city` (`Id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`product` (
  `Id_pro` INT NOT NULL AUTO_INCREMENT,
  `Cod_pro` VARCHAR(10) NULL,
  `PaNu_pro` VARCHAR(250) NULL,
  `Nam_pro` VARCHAR(250) NULL,
  `Mod_pro` VARCHAR(250) NULL,
  `Man_pro` VARCHAR(250) NULL,
  `Det_pro` VARCHAR(500) NULL,
  `Dat_pro` VARCHAR(10) NULL,
  `Sto_pro` INT NULL,
  `Sta_pro` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_pro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`receipt` (
  `Id_rece` INT NOT NULL AUTO_INCREMENT,
  `Dat_rece` VARCHAR(10) NULL,
  `Det_rece` VARCHAR(500) NULL,
  `Tot_rece` INT NULL,
  `Qua_rece` INT NULL,
  `ActSto_rece` INT NULL,
  `Sta_rece` VARCHAR(5) NULL,
  `warehouse_Id_wh` INT NOT NULL,
  `product_Id_pro` INT NOT NULL,
  PRIMARY KEY (`Id_rece`),
  INDEX `fk_receipt_warehouse1_idx` (`warehouse_Id_wh` ASC),
  INDEX `fk_receipt_product1_idx` (`product_Id_pro` ASC),
  CONSTRAINT `fk_receipt_warehouse1`
    FOREIGN KEY (`warehouse_Id_wh`)
    REFERENCES `hejevero_principal`.`warehouse` (`Id_wh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receipt_product1`
    FOREIGN KEY (`product_Id_pro`)
    REFERENCES `hejevero_principal`.`product` (`Id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`family` (
  `Id_fam` INT NOT NULL AUTO_INCREMENT,
  `Nam_fam` VARCHAR(250) NULL,
  `Sta_fam` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_fam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`product_family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`product_family` (
  `Id_pf` INT NOT NULL AUTO_INCREMENT,
  `Sta_pf` VARCHAR(5) NULL,
  `product_Id_pro` INT NOT NULL,
  `family_Id_fam` INT NOT NULL,
  PRIMARY KEY (`Id_pf`),
  INDEX `fk_product_family_product2_idx` (`product_Id_pro` ASC),
  INDEX `fk_product_family_family2_idx` (`family_Id_fam` ASC),
  CONSTRAINT `fk_product_family_product2`
    FOREIGN KEY (`product_Id_pro`)
    REFERENCES `hejevero_principal`.`product` (`Id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_family_family2`
    FOREIGN KEY (`family_Id_fam`)
    REFERENCES `hejevero_principal`.`family` (`Id_fam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`extra` (
  `Id_ext` INT NOT NULL AUTO_INCREMENT,
  `Nam_ext` VARCHAR(250) NULL,
  `Det_ext` VARCHAR(500) NULL,
  `Typ_ext` VARCHAR(250) NULL,
  `Sta_ext` VARCHAR(5) NULL,
  `product_Id_pro` INT NOT NULL,
  PRIMARY KEY (`Id_ext`),
  INDEX `fk_extra_product2_idx` (`product_Id_pro` ASC),
  CONSTRAINT `fk_extra_product2`
    FOREIGN KEY (`product_Id_pro`)
    REFERENCES `hejevero_principal`.`product` (`Id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`price` (
  `Id_price` INT NOT NULL AUTO_INCREMENT,
  `Cod_price` VARCHAR(10) NULL,
  `Start_dat_price` VARCHAR(10) NULL,
  `End_dat_price` VARCHAR(10) NULL,
  `New_price` INT NULL,
  `Sta_price` VARCHAR(5) NULL,
  `product_Id_pro` INT NOT NULL,
  PRIMARY KEY (`Id_price`),
  INDEX `fk_price_product3_idx` (`product_Id_pro` ASC),
  CONSTRAINT `fk_price_product3`
    FOREIGN KEY (`product_Id_pro`)
    REFERENCES `hejevero_principal`.`product` (`Id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`serial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`serial` (
  `Id_serial` INT NOT NULL AUTO_INCREMENT,
  `Cod_serial` VARCHAR(10) NULL,
  `Sta_serial` VARCHAR(5) NULL,
  `receipt_Id_rece` INT NOT NULL,
  PRIMARY KEY (`Id_serial`),
  INDEX `fk_serial_receipt1_idx` (`receipt_Id_rece` ASC),
  CONSTRAINT `fk_serial_receipt1`
    FOREIGN KEY (`receipt_Id_rece`)
    REFERENCES `hejevero_principal`.`receipt` (`Id_rece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`sell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`sell` (
  `Id_sell` INT NOT NULL AUTO_INCREMENT,
  `Det_sell` VARCHAR(500) NULL,
  `Dat_sell` VARCHAR(10) NULL,
  `Tot_sell` INT NULL,
  `Net_sell` INT NULL,
  `Iva_sell` INT NULL,
  `Sta_sell` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_sell`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`serial_sell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`serial_sell` (
  `Id_ss` INT NOT NULL AUTO_INCREMENT,
  `Dat_ss` VARCHAR(10) NULL,
  `Sta_ss` VARCHAR(5) NULL,
  `sell_Id_sell` INT NOT NULL,
  `serial_Id_serial` INT NOT NULL,
  PRIMARY KEY (`Id_ss`),
  INDEX `fk_serial_sell_sell1_idx` (`sell_Id_sell` ASC),
  INDEX `fk_serial_sell_serial1_idx` (`serial_Id_serial` ASC),
  CONSTRAINT `fk_serial_sell_sell1`
    FOREIGN KEY (`sell_Id_sell`)
    REFERENCES `hejevero_principal`.`sell` (`Id_sell`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serial_sell_serial1`
    FOREIGN KEY (`serial_Id_serial`)
    REFERENCES `hejevero_principal`.`serial` (`Id_serial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`client_sell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`client_sell` (
  `Id_cs` INT NOT NULL AUTO_INCREMENT,
  `Sta_cs` VARCHAR(5) NULL,
  `sell_Id_sell` INT NOT NULL,
  `user-data_Id_ud` INT NOT NULL,
  PRIMARY KEY (`Id_cs`),
  INDEX `fk_client_sell_sell2_idx` (`sell_Id_sell` ASC),
  INDEX `fk_client_sell_user-data1_idx` (`user-data_Id_ud` ASC),
  CONSTRAINT `fk_client_sell_sell2`
    FOREIGN KEY (`sell_Id_sell`)
    REFERENCES `hejevero_principal`.`sell` (`Id_sell`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_sell_user-data1`
    FOREIGN KEY (`user-data_Id_ud`)
    REFERENCES `hejevero_principal`.`user_data` (`Id_ud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`config` (
  `Id_conf` INT NOT NULL AUTO_INCREMENT,
  `Nam_conf` VARCHAR(250) NULL,
  `Det_conf` VARCHAR(500) NULL,
  `Rol_conf` VARCHAR(45) NULL,
  `Sta_conf` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_conf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`user_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`user_config` (
  `Id_cu` INT NOT NULL AUTO_INCREMENT,
  `Nam_cu` VARCHAR(250) NULL,
  `Val_cu` VARCHAR(500) NULL,
  `Sta_cu` VARCHAR(5) NULL,
  `user_Id_user` INT NOT NULL,
  `config_Id_conf` INT NOT NULL,
  PRIMARY KEY (`Id_cu`),
  INDEX `fk_user_config_user1_idx` (`user_Id_user` ASC),
  INDEX `fk_user_config_config1_idx` (`config_Id_conf` ASC),
  CONSTRAINT `fk_user_config_user1`
    FOREIGN KEY (`user_Id_user`)
    REFERENCES `hejevero_principal`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_config_config1`
    FOREIGN KEY (`config_Id_conf`)
    REFERENCES `hejevero_principal`.`config` (`Id_conf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`post_user_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`post_user_data` (
  `Id_pud` INT NOT NULL AUTO_INCREMENT,
  `Sta_pud` VARCHAR(5) NULL,
  `user_data_Id_ud` INT NOT NULL,
  `post_Id_post` INT NOT NULL,
  PRIMARY KEY (`Id_pud`),
  INDEX `fk_post_user-data_user-data1_idx` (`user_data_Id_ud` ASC),
  INDEX `fk_post_user-data_post1_idx` (`post_Id_post` ASC),
  CONSTRAINT `fk_post_user-data_user-data1`
    FOREIGN KEY (`user_data_Id_ud`)
    REFERENCES `hejevero_principal`.`user_data` (`Id_ud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user-data_post1`
    FOREIGN KEY (`post_Id_post`)
    REFERENCES `hejevero_principal`.`post` (`Id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero_principal`.`detail_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero_principal`.`detail_user` (
  `Id_du` INT NOT NULL AUTO_INCREMENT,
  `Nam_du` VARCHAR(250) NULL,
  `Sta_du` VARCHAR(45) NULL,
  `Det_du` VARCHAR(500) NULL,
  `SDe_du` VARCHAR(500) NULL,
  `Dat_du` VARCHAR(45) NULL,
  `user_data_Id_ud` INT NOT NULL,
  PRIMARY KEY (`Id_du`),
  INDEX `fk_detail_user_user-data1_idx` (`user_data_Id_ud` ASC),
  CONSTRAINT `fk_detail_user_user-data1`
    FOREIGN KEY (`user_data_Id_ud`)
    REFERENCES `hejevero_principal`.`user_data` (`Id_ud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
